### ISSUE TITLE
can you explain or can you give some on dsa bro ?

### ISSUE THREAD

**Issue by SunilKumar-K** [Abhaydutt2003/DataStructureAndAlgoPractice#1]
plzz give some tips and resources to me bro to learn dsa concepts bro

**Comment by Abhaydutt2003** [comment]
sorry to answer so late.
you can simply start of by doing the top 150 leetcode questions.The coding ninjas course for dsa is pretty good if you are into courses.
I have made my own custom list to solve dsa questions in a pattern, if you want it , you can tell me ill share with you.
No one becomes perfect in dsa. After putting almost 1.5 years in dsa, i still think i am not perfect
Best of luck
